import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
	ApolloClient,
	InMemoryCache,
	ApolloProvider,
	createHttpLink,
} from "@apollo/client";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Hardsho App",
	description: "Generated by create next app",
};

const httpLink = createHttpLink({
	uri: "http://localhost:4000/",
});

const client = new ApolloClient({
	link: httpLink,
	cache: new InMemoryCache(),
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ApolloProvider client={client}>
			<html lang="en">
				<body className={inter.className}>{children}</body>
			</html>
		</ApolloProvider>
	);
}
